import fs from 'node:fs/promises';
import http from 'node:http';
import vm from 'node:vm';
import {chromium} from 'playwright';
const js=await fs.readFile('scripts/challenge-live.js','utf8');
const fn=js.slice(js.indexOf('function hjChFigureArt('),js.indexOf('function hjChLms(model)'));
const art=vm.runInNewContext(fn+';hjChFigureArt',{esc:s=>String(s).replaceAll('"','&quot;')});
const names=['MISBA','BRYAN','TYLER','NATHAN M','WASI','CESAR','NATHAN T','GARRETT','JARRETT','KAT'];
const make=pose=>'<section class="'+(pose==='seated'?'opt-view ':'')+'lms-view"><div class="lineup" style="--lineup-count:10"><div class="lineup-row">'+names.map((short,i)=>'<div class="lineup-figure '+(pose==='seated'?'is-seated ':'')+(i===3?'is-leader':'')+'">'+art({short},'proof-'+i,i===3,pose)+'<span class="lineup-label"><span class="lineup-name">'+short+'</span></span></div>').join('')+(pose==='seated'?'<div class="opt-bench"><i class="opt-bench-seat"></i>'+[4,26,50,74,96].map(x=>'<i class="opt-bench-leg" style="left:'+x+'%"></i>').join('')+'</div>':'')+'</div></div></section>';
const pageHtml='<!doctype html><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/styles/season-challenges.css"><style>:root{--sans:Arial;--navy:#16334b;--brass:#b38b36;--brass-bright:#d9a93f}*{box-sizing:border-box}body{margin:20px;background:#f9efd9;color:#16334b;font-family:Arial}section{margin:20px 0;container-type:inline-size} .lineup-label{font-weight:bold}</style>'+make('standing')+make('seated');
const server=http.createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(pageHtml);return;}const p='.'+req.url;res.setHeader('Content-Type',p.endsWith('.css')?'text/css':'image/webp');res.end(await fs.readFile(p));}catch(e){res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(8765,r));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1500,height:740}});
await page.goto('http://localhost:8765/');
await page.waitForTimeout(700);
await page.screenshot({path:'.manager-art/site-proof.png',fullPage:true});
console.log('Rendered standing and seated figures with the shared site CSS');
await browser.close();server.close();
